apiVersion: v1
kind: Secret
metadata:
  name: example-creds-full
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    {
      "pm_api_url": "https://proxmox.example.com:8006/api2/json",
      "pm_api_token_id": "your-token-id",
      "pm_api_token_secret": "your-token-secret",
      "pm_debug": true,
      "pm_dangerously_ignore_unknown_attributes": false
    } 