name: Build and Push AMD64 Artifacts

on:
  push:
    branches: ['main', 'master', 'release-*', 'method1-local-generated']
    tags: ['v*']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      TERRAFORM_VERSION: "1.5.7"
      TERRAFORM_PROVIDER_SOURCE: "registry.terraform.io/joekky/proxmox"
      TERRAFORM_PROVIDER_VERSION: "0.1.0"
      BUILD_REGISTRY: "ghcr.io/${{ github.repository }}"
      ARCH: "amd64"
      VERSION: "${{ github.ref_name }}"
      IMAGE_NAME: "ghcr.io/${{ github.repository }}/provider-proxmox-crossplane-amd64"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build Provider Binary
        run: |
          make build SKIP_GENERATE=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Build AMD64 Docker Image
        run: |
          TARGETOS=linux TARGETARCH=amd64 make image.build SKIP_GENERATE=true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker Image to GHCR
        run: |
          # Tag the image with version
          docker tag "${IMAGE_NAME}" "${IMAGE_NAME}:${VERSION}"
          # Push both latest and versioned tags
          docker push "${IMAGE_NAME}:${VERSION}"

      - name: Install Crossplane CLI
        run: |
          curl -sL https://raw.githubusercontent.com/crossplane/crossplane/master/install.sh | sh
          sudo mv kubectl-crossplane /usr/local/bin
          chmod +x /usr/local/bin/kubectl-crossplane

      - name: Build AMD64 XPKG
        run: |
          ARCH=amd64 OS=linux make xpkg.build